# Kernel SVM

## Importing the libraries

In [78]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [79]:
dataset = pd.read_csv('heart_disease_cleaned.csv')
X = dataset.iloc[:, [1,4,5,6,9,13]].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [81]:
X_train_df = pd.DataFrame(X_train)

print("X_train yang rapi:")
print(X_train_df)

X_train yang rapi:
        0    1           2      3           4         5
0    58.0  0.0  130.000000  197.0  131.000000  0.000000
1    54.0  1.0  110.000000  208.0  142.000000  0.676375
2    61.0  2.0  150.000000  243.0  137.000000  0.000000
3    44.0  0.0  130.000000  290.0  100.000000  0.676375
4    54.0  0.0  200.000000  198.0  142.000000  0.676375
..    ...  ...         ...    ...         ...       ...
685  64.0  0.0  132.132404  306.0  137.545665  0.676375
686  43.0  0.0  132.000000  247.0  143.000000  0.676375
687  51.0  0.0  130.000000    0.0  170.000000  0.676375
688  47.0  2.0  135.000000  248.0  170.000000  0.676375
689  61.0  0.0  130.000000    0.0  115.000000  0.676375

[690 rows x 6 columns]


In [82]:
print(y_train)

[0 0 0 1 1 0 0 1 0 2 0 3 0 2 3 3 1 0 1 0 1 0 2 0 0 0 2 3 1 1 0 0 2 4 0 1 0
 1 0 1 3 0 0 0 0 0 1 0 0 0 2 2 0 2 0 2 1 1 3 0 2 3 2 1 3 1 3 3 0 3 0 4 2 1
 1 2 1 0 1 0 0 1 0 0 3 2 0 2 1 3 0 0 0 0 0 1 1 1 2 0 0 2 0 2 2 0 0 0 0 3 0
 3 3 1 0 0 0 1 1 1 1 3 4 0 0 0 1 1 1 0 1 0 1 4 1 0 1 1 0 1 1 0 1 1 4 0 1 1
 0 1 0 0 1 2 0 1 3 2 0 0 0 1 0 1 0 0 2 1 3 0 0 0 3 1 3 0 1 0 0 0 0 0 1 1 0
 1 0 3 0 1 1 0 3 1 0 0 2 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 2 2 1 3 0 1 2 3 0
 1 1 0 3 0 1 0 0 0 0 4 1 0 3 1 0 0 1 3 1 0 0 0 0 2 0 3 3 1 1 2 1 1 0 0 2 2
 1 1 0 0 1 1 0 1 1 0 1 2 3 0 0 0 0 0 1 0 1 0 0 1 3 0 1 0 4 0 0 2 1 0 0 0 1
 0 1 3 1 3 2 3 0 1 2 2 2 0 2 0 4 1 0 1 1 0 1 0 0 0 3 1 1 1 1 3 3 1 4 0 0 0
 3 3 0 0 0 1 0 1 2 1 0 3 3 0 1 0 0 0 3 2 3 1 1 1 1 0 0 2 0 0 0 3 1 0 0 0 0
 1 2 0 2 1 2 2 3 3 1 0 0 2 1 1 2 1 0 0 1 2 0 1 0 0 3 2 0 0 3 1 1 3 3 0 1 0
 1 1 1 0 0 0 4 0 3 2 1 2 3 0 1 0 0 1 2 3 2 2 4 0 2 0 3 1 4 3 1 2 0 0 1 0 0
 2 1 0 1 0 1 1 0 1 1 1 1 0 0 3 0 1 3 3 1 1 0 1 1 0 1 2 0 1 3 0 0 0 4 0 0 0
 0 1 0 3 0 1 1 4 1 1 1 1 

In [83]:
X_test_df = pd.DataFrame(X_test)

print("X_test yang rapi:")
print(X_test_df)

X_test yang rapi:
        0    1      2           3      4         5
0    30.0  3.0  170.0  237.000000  170.0  0.676375
1    68.0  0.0  135.0    0.000000  120.0  0.676375
2    45.0  3.0  110.0  264.000000  132.0  0.000000
3    55.0  2.0  120.0  220.000000  134.0  0.676375
4    51.0  2.0  120.0  295.000000  157.0  0.000000
..    ...  ...    ...         ...    ...       ...
225  41.0  1.0  120.0  295.000000  170.0  0.676375
226  59.0  0.0  174.0  249.000000  143.0  0.000000
227  58.0  2.0  140.0  179.000000  160.0  0.676375
228  38.0  1.0  120.0  275.000000  129.0  0.676375
229  38.0  0.0  110.0  199.130337  150.0  0.676375

[230 rows x 6 columns]


In [84]:
print(y_test)

[0 3 1 0 0 0 2 0 0 2 1 0 0 2 1 0 1 0 1 0 0 2 0 1 4 2 0 2 1 0 0 0 3 3 0 0 0
 3 0 3 1 1 1 1 0 2 0 0 1 0 0 2 4 0 0 0 1 0 0 2 3 0 4 0 0 2 0 1 1 2 1 1 1 0
 0 0 0 3 1 0 0 2 3 0 1 0 0 2 1 1 0 3 0 0 0 0 0 1 0 0 1 0 3 0 1 2 2 0 1 2 2
 1 1 0 2 3 0 0 2 1 1 3 1 2 3 1 0 4 2 0 0 0 1 1 1 3 1 1 2 0 1 0 1 0 1 0 1 0
 0 0 1 1 1 2 2 1 3 0 1 4 0 1 0 0 0 1 1 3 0 0 0 0 2 1 3 2 2 2 0 4 2 1 1 0 0
 0 0 0 0 0 1 3 0 0 2 0 2 2 0 0 0 1 3 0 0 1 0 4 0 2 0 0 3 0 0 2 1 0 1 1 1 0
 0 1 4 0 1 0 0 1]


## Feature Scaling

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [86]:
X_train_df = pd.DataFrame(X_train)

print("X_train yang rapi:")
print(X_train_df)

X_train yang rapi:
            0         1         2         3         4         5
0    0.488302 -0.823735 -0.130934 -0.007482 -0.279766 -1.214020
1    0.062215  0.236670 -1.248304  0.093728  0.155499  0.024765
2    0.807867  1.297075  0.986436  0.415762 -0.042349 -1.214020
3   -1.003003 -0.823735 -0.130934  0.848208 -1.506422  0.024765
4    0.062215 -0.823735  3.779862  0.001718  0.155499  0.024765
..        ...       ...       ...       ...       ...       ...
685  1.127433 -0.823735 -0.011800  0.995423 -0.020757  0.024765
686 -1.109525 -0.823735 -0.019197  0.452566  0.195069  0.024765
687 -0.257350 -0.823735 -0.130934 -1.820073  1.263447  0.024765
688 -0.683438  1.297075  0.148409  0.461767  1.263447  0.024765
689  0.807867 -0.823735 -0.130934 -1.820073 -0.912879  0.024765

[690 rows x 6 columns]


In [87]:
X_test_df = pd.DataFrame(X_test)

print("X_test yang rapi:")
print(X_test_df)

X_test yang rapi:
            0         1         2         3         4         5
0   -2.494308  2.357479  2.103807  0.360556  1.263447  0.024765
1    1.553520 -0.823735  0.148409 -1.820073 -0.715031  0.024765
2   -0.896481  2.357479 -1.248304  0.608982 -0.240197 -1.214020
3    0.168737  1.297075 -0.689619  0.204140 -0.161057  0.024765
4   -0.257350  1.297075 -0.689619  0.894212  0.749042 -1.214020
..        ...       ...       ...       ...       ...       ...
225 -1.322568  0.236670 -0.689619  0.894212  1.263447  0.024765
226  0.594824 -0.823735  2.327281  0.470968  0.195069 -1.214020
227  0.488302  1.297075  0.427751 -0.173100  0.867751  0.024765
228 -1.642133  0.236670 -0.689619  0.710193 -0.358905  0.024765
229 -1.642133 -0.823735 -1.248304  0.012119  0.472055  0.024765

[230 rows x 6 columns]


## Training the Kernel SVM model on the Training set

In [88]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting a new result

In [89]:
print(classifier.predict(sc.transform([[60,0,130,206,132,2]])))

[3]


## Predicting the Test set results

In [90]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 3]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [3 2]
 [0 0]
 [0 0]
 [3 2]
 [0 1]
 [0 0]
 [0 0]
 [3 2]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 2]
 [0 0]
 [0 1]
 [3 4]
 [3 2]
 [0 0]
 [1 2]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [3 3]
 [1 3]
 [0 0]
 [0 0]
 [1 0]
 [1 3]
 [0 0]
 [0 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 2]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 2]
 [1 4]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 2]
 [1 3]
 [0 0]
 [1 4]
 [0 0]
 [0 0]
 [0 2]
 [0 0]
 [1 1]
 [0 1]
 [0 2]
 [3 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 3]
 [1 1]
 [0 0]
 [1 0]
 [1 2]
 [3 3]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [3 2]
 [1 1]
 [1 1]
 [1 0]
 [1 3]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [3 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 3]
 [1 0]
 [1 1]
 [1 2]
 [1 2]
 [0 0]
 [1 1]
 [3 2]
 [1 2]
 [0 1]
 [1 1]
 [0 0]
 [1 2]
 [0 3]
 [1 0]
 [0 0]
 [3 2]
 [0 1]
 [1 1]
 [1 3]
 [0 1]
 [3 2]
 [0 3]
 [1 1]
 [0 0]
 [1 4]
 [0 2]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 3]
 [1 1]
 [0 1]
 [1 2]
 [0 0]
 [0 1]
 [0 0]
 [1 1]

## Making the Confusion Matrix

In [91]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
num_classes = cm.shape[0]
metrics_per_class = {}

for i in range(num_classes):
    tp = cm[i, i]
    fp = cm[:, i].sum() - tp
    fn = cm[i, :].sum() - tp
    tn = cm.sum() - (tp + fp + fn)

    metrics_per_class[i] = {
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "TN": tn
    }

# Tampilkan hasil per kelas
for class_label, metrics in metrics_per_class.items():
    print(f"\nKelas {class_label}:")
    print(f"  True Positive (TP): {metrics['TP']}")
    print(f"  False Positive (FP): {metrics['FP']}")
    print(f"  False Negative (FN): {metrics['FN']}")
    print(f"  True Negative (TN): {metrics['TN']}")

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAkurasi Keseluruhan: {accuracy}")

Confusion Matrix:
 [[82 24  0  0  0]
 [15 42  0  5  0]
 [ 8 15  0 11  0]
 [ 3 13  0  4  0]
 [ 1  5  0  2  0]]

Kelas 0:
  True Positive (TP): 82
  False Positive (FP): 27
  False Negative (FN): 24
  True Negative (TN): 97

Kelas 1:
  True Positive (TP): 42
  False Positive (FP): 57
  False Negative (FN): 20
  True Negative (TN): 111

Kelas 2:
  True Positive (TP): 0
  False Positive (FP): 0
  False Negative (FN): 34
  True Negative (TN): 196

Kelas 3:
  True Positive (TP): 4
  False Positive (FP): 18
  False Negative (FN): 16
  True Negative (TN): 192

Kelas 4:
  True Positive (TP): 0
  False Positive (FP): 0
  False Negative (FN): 8
  True Negative (TN): 222

Akurasi Keseluruhan: 0.5565217391304348
